<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../NetWasm.Compiler.Core/NetWasm.Compiler.Core.csproj" />
    <ProjectReference Include="../NetWasm.Compiler.ControlFlow/NetWasm.Compiler.ControlFlow.csproj" />
  </ItemGroup>
</Project>
