#ifndef NETWASM_NATIVE_TARGET_H
#define NETWASM_NATIVE_TARGET_H

#include <stdint.h>

typedef uint32_t netwasm_id_t;
typedef uintptr_t netwasm_address_t;
typedef netwasm_address_t netwasm_reference_t;

enum {
    NETWASM_TYPE_ID_SIZE = sizeof(netwasm_id_t),
    NETWASM_SEMANTIC_LENGTH_SIZE = sizeof(uint32_t),
    NETWASM_OBJECT_REFERENCE_SIZE = sizeof(netwasm_reference_t),
    NETWASM_OBJECT_HEADER_SIZE = sizeof(netwasm_reference_t)
};

#if defined(__wasm64__)
#define NETWASM_MEMORY64 1
#else
#define NETWASM_MEMORY64 0
#endif

static inline netwasm_address_t netwasm_align_address(
    netwasm_address_t value,
    netwasm_address_t alignment)
{
    return (value + alignment - 1) & ~(alignment - 1);
}

enum {
    NETWASM_STRING_LENGTH_OFFSET = NETWASM_OBJECT_HEADER_SIZE,
    NETWASM_STRING_DATA_OFFSET =
        NETWASM_STRING_LENGTH_OFFSET + NETWASM_SEMANTIC_LENGTH_SIZE,
    NETWASM_STRING_MIN_OBJECT_SIZE = NETWASM_STRING_DATA_OFFSET,
    NETWASM_ARRAY_LENGTH_OFFSET = NETWASM_OBJECT_HEADER_SIZE,
    NETWASM_ARRAY_DATA_POINTER_OFFSET =
        (NETWASM_ARRAY_LENGTH_OFFSET + NETWASM_SEMANTIC_LENGTH_SIZE +
         NETWASM_OBJECT_REFERENCE_SIZE - 1) &
        ~(NETWASM_OBJECT_REFERENCE_SIZE - 1),
    NETWASM_ARRAY_ELEMENT_TYPE_ID_OFFSET =
        NETWASM_ARRAY_DATA_POINTER_OFFSET + NETWASM_OBJECT_REFERENCE_SIZE,
    NETWASM_ARRAY_OBJECT_SIZE =
        (NETWASM_ARRAY_ELEMENT_TYPE_ID_OFFSET + sizeof(netwasm_id_t) +
         NETWASM_OBJECT_REFERENCE_SIZE - 1) &
        ~(NETWASM_OBJECT_REFERENCE_SIZE - 1),
    NETWASM_RECTANGULAR_ARRAY_RANK_OFFSET =
        NETWASM_ARRAY_ELEMENT_TYPE_ID_OFFSET + sizeof(netwasm_id_t),
    NETWASM_RECTANGULAR_ARRAY_SHAPE_POINTER_OFFSET =
        (NETWASM_RECTANGULAR_ARRAY_RANK_OFFSET + sizeof(uint32_t) +
         NETWASM_OBJECT_REFERENCE_SIZE - 1) &
        ~(NETWASM_OBJECT_REFERENCE_SIZE - 1),
    NETWASM_RECTANGULAR_ARRAY_OBJECT_SIZE =
        NETWASM_RECTANGULAR_ARRAY_SHAPE_POINTER_OFFSET +
        NETWASM_OBJECT_REFERENCE_SIZE,
    NETWASM_MAX_ARRAY_RANK = 32,
    NETWASM_RECTANGULAR_ARRAY_DIMENSION_SIZE = sizeof(uint32_t) * 2,
    NETWASM_RECTANGULAR_ARRAY_DIMENSION_LENGTH_OFFSET = 0,
    NETWASM_RECTANGULAR_ARRAY_DIMENSION_STRIDE_OFFSET = sizeof(uint32_t)
};

#endif
