using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using NetWasm.Hosting.Deployment;

namespace NetWasm.Wit.Bindings.Workers;

public sealed record WitWorkerCSharpClientRequest(
    ReadOnlyMemory<byte> ContractJson, string Namespace, string ClassName,
    string JavaScriptModule, string WorkerClientModule);

public sealed record WitWorkerCSharpClientSource(byte[] CSharp, byte[] JavaScript);

public interface IWitWorkerCSharpClientWriter
{
    WitWorkerCSharpClientSource Write(WitWorkerCSharpClientRequest request);
}

/// <summary>Reuses WIT declarations and existing opaque interop handles for a private byte bridge.</summary>
public sealed class WitWorkerCSharpClientWriter(
    IWitWorkerContractReader contracts,
    IWitWorkerCSharpContractProjector projector,
    IWitTypeDeclarationWriter declarations,
    IWitBindingSyntaxFormatter syntax,
    ImmutableDictionary<string, IWitWorkerValueCodecWriter> codecs) : IWitWorkerCSharpClientWriter
{
    private readonly IWitWorkerContractReader _contracts = contracts ?? throw new ArgumentNullException(nameof(contracts));
    private readonly IWitWorkerCSharpContractProjector _projector = projector ?? throw new ArgumentNullException(nameof(projector));
    private readonly IWitTypeDeclarationWriter _declarations = declarations ?? throw new ArgumentNullException(nameof(declarations));
    private readonly IWitBindingSyntaxFormatter _syntax = syntax ?? throw new ArgumentNullException(nameof(syntax));
    private readonly ImmutableDictionary<string, IWitWorkerValueCodecWriter> _codecs = codecs ?? throw new ArgumentNullException(nameof(codecs));

    public WitWorkerCSharpClientSource Write(WitWorkerCSharpClientRequest request)
    {
        ArgumentNullException.ThrowIfNull(request);
        if (!request.Namespace.Split('.').All(ValidIdentifier) || !ValidIdentifier(request.ClassName)
            || string.IsNullOrWhiteSpace(request.JavaScriptModule)
            || !request.WorkerClientModule.StartsWith("./", StringComparison.Ordinal)
            || request.WorkerClientModule.Split('/').Skip(1).Any(part => part is "" or "." or "..")
            || request.WorkerClientModule.Any(character => character is '\\' or '#' or '?'))
            throw new ArgumentException("Worker C# client publication contract is invalid", nameof(request));
        var projected = _projector.Project(_contracts.Read(request.ContractJson));
        var fingerprint = Convert.ToHexStringLower(SHA256.HashData(request.ContractJson.Span));
        var cs = new StringBuilder(); var js = new StringBuilder();
        cs.AppendLine("// <auto-generated />\n#nullable enable\nusing System;\nusing System.Threading;\nusing System.Threading.Tasks;\nusing System.Runtime.InteropServices.JavaScript;\nusing System.Runtime.InteropServices.WebAssembly;");
        cs.AppendLine(CultureInfo.InvariantCulture, $"namespace {request.Namespace};");
        cs.AppendLine(CultureInfo.InvariantCulture, $"public sealed class {request.ClassName} : IDisposable\n{{");
        cs.Append(_declarations.Generate(projected.Document, projected.World));
        cs.AppendLine(CultureInfo.InvariantCulture, $"private const string ContractFingerprint = {WitWorkerValueCodecRequest.Json(fingerprint)};");
        cs.AppendLine("private readonly JSObject _session; private bool _closed; private bool _released; private Task? _closing;");
        cs.AppendLine(CultureInfo.InvariantCulture, $"private {request.ClassName}(JSObject session) => _session = session;");
        cs.AppendLine(CultureInfo.InvariantCulture, $"[JSImport(\"create\", {WitWorkerValueCodecRequest.Json(request.JavaScriptModule)})] private static extern JSObject Create();");
        cs.AppendLine(CultureInfo.InvariantCulture, $"[JSImport(\"terminate\", {WitWorkerValueCodecRequest.Json(request.JavaScriptModule)})] private static extern void Terminate(JSObject session);");
        cs.AppendLine(CultureInfo.InvariantCulture, $"[JSImport(\"beginCall\", {WitWorkerValueCodecRequest.Json(request.JavaScriptModule)})] private static extern JSObject BeginCall(JSObject session, byte[] bytes);");
        cs.AppendLine(CultureInfo.InvariantCulture, $"[JSImport(\"cancel\", {WitWorkerValueCodecRequest.Json(request.JavaScriptModule)})] private static extern void Cancel(JSObject invocation);");
        cs.AppendLine(CultureInfo.InvariantCulture, $"[JSImportPromise(\"call\", {WitWorkerValueCodecRequest.Json(request.JavaScriptModule)})] private static extern JSSubscription Call(JSObject invocation, Action<byte[]> completed, Action rejected);");
        cs.AppendLine(CultureInfo.InvariantCulture, $"public static async Task<{request.ClassName}> CreateAsync(CancellationToken cancellationToken = default)\n{{");
        cs.AppendLine("cancellationToken.ThrowIfCancellationRequested();");
        cs.AppendLine(CultureInfo.InvariantCulture, $"var client = new {request.ClassName}(Create());");
        cs.AppendLine("try { var response = Response(await Invoke(client._session, Request(0).Bytes, cancellationToken)); response.End(); return client; } catch { client.Dispose(); throw; } }");
        cs.AppendLine(ClientLifetime);
        js.AppendLine(CultureInfo.InvariantCulture, $"const contractFingerprint = {WitWorkerValueCodecRequest.Json(fingerprint)};");
        js.AppendLine(CultureInfo.InvariantCulture, $"const workerClientModule = {WitWorkerValueCodecRequest.Json(request.WorkerClientModule)};");
        js.AppendLine(JavaScriptLifetime);
        var operations = projected.Contract.Exports;
        var methodNames = new HashSet<string>(StringComparer.Ordinal) { "Create", "CreateAsync", "Dispose", "DisposeAsync" };
        var requests = new WitWorkerValueCodecRequest(0, projected, _syntax);
        js.AppendLine("async function execute(owner, bytes, signal) { try { const reader = new WireReader(bytes); checkHeader(reader); const action = readu32(reader);");
        js.AppendLine("if (action === 0) { reader.end(); await owner.ready; return response().bytes; }");
        js.AppendLine("if (action === 2) { reader.end(); await owner.close(); return response().bytes; }");
        js.AppendLine("if (action !== 1) throw invalidWire(); switch (readu32(reader)) {");
        for (var index = 0; index < operations.Length; index++)
        {
            var export = operations[index]!;
            var method = _syntax.Format(new WitBindingSyntaxRequest.FunctionName(export.Function!)) + "Async";
            if (!methodNames.Add(method))
            {
                method = _syntax.Format(new WitBindingSyntaxRequest.Identifier(export.Function!)) + "_"
                    + Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(export.Operation!)))[..12] + "Async";
                if (!methodNames.Add(method)) throw new InvalidDataException("Worker C# method names collide");
            }
            var resultType = export.Result is null ? "Task" : "Task<" + requests.Type(export.Result) + ">";
            var parameters = export.Parameters.Select((parameter, number) => $"{requests.Type(parameter!.Type!)} argument{number}")
                .Append("CancellationToken cancellationToken = default");
            cs.AppendLine(CultureInfo.InvariantCulture, $"public async {resultType} {method}({string.Join(", ", parameters)}) {{");
            cs.AppendLine(CultureInfo.InvariantCulture, $"if (_closed) throw new ObjectDisposedException(nameof({request.ClassName})); cancellationToken.ThrowIfCancellationRequested(); var writer = Request(1); Writeu32(writer, {index}u);");
            foreach (var (parameter, number) in export.Parameters.Select((parameter, number) => (parameter!, number)))
                cs.AppendLine(CultureInfo.InvariantCulture, $"Write{WitWorkerValueCodecRequest.Suffix(parameter.Type!)}(writer, argument{number});");
            cs.AppendLine("var reader = Response(await Invoke(_session, writer.Bytes, cancellationToken));");
            if (export.Result is not null)
                cs.AppendLine(CultureInfo.InvariantCulture, $"var result = Read{WitWorkerValueCodecRequest.Suffix(export.Result)}(reader); reader.End(); return result;");
            else cs.AppendLine("reader.End();");
            cs.AppendLine("}");
            js.AppendLine(CultureInfo.InvariantCulture, $"case {index}: {{");
            var reads = export.Parameters.Select(parameter => "read" + WitWorkerValueCodecRequest.Suffix(parameter!.Type!) + "(reader)");
            js.AppendLine(CultureInfo.InvariantCulture, $"const args = [{string.Join(", ", reads)}]; reader.end(); const client = await owner.ready; const result = await client[{WitWorkerValueCodecRequest.Json(export.Operation!)}](...args, {{ signal }}); const writer = response();");
            if (export.Result is not null)
                js.AppendLine(CultureInfo.InvariantCulture, $"write{WitWorkerValueCodecRequest.Suffix(export.Result)}(writer, result);");
            js.AppendLine("return writer.bytes; }");
        }
        js.AppendLine("default: throw invalidWire(); } } catch (cause) { const writer = response(1); writestring(writer, typeof cause?.message === 'string' ? cause.message : String(cause)); return writer.bytes; } }");
        foreach (var (id, layout) in projected.Layouts.OrderBy(item => item.Key))
        {
            var input = new WitWorkerValueCodecRequest(id, projected, _syntax);
            var codec = _codecs[layout.Kind].Write(input);
            cs.AppendLine(CultureInfo.InvariantCulture, $"private static void WriteType{id}(WireWriter writer, {input.Name} value) {{ {codec.CSharpWrite} }}");
            cs.AppendLine(CultureInfo.InvariantCulture, $"private static {input.Name} ReadType{id}(WireReader reader) {{ {codec.CSharpRead} }}");
            js.AppendLine(CultureInfo.InvariantCulture, $"function writeType{id}(writer, value) {{ {codec.JavaScriptWrite} }}");
            js.AppendLine(CultureInfo.InvariantCulture, $"function readType{id}(reader) {{ {codec.JavaScriptRead} }}");
        }
        cs.AppendLine(CSharpHeader); cs.AppendLine(WitWorkerByteCodecSource.CSharp); cs.AppendLine("}");
        js.AppendLine(JavaScriptHeader); js.AppendLine(WitWorkerByteCodecSource.JavaScript);
        return new(Encoding.UTF8.GetBytes(cs.ToString().ReplaceLineEndings("\n")),
            Encoding.UTF8.GetBytes(js.ToString().ReplaceLineEndings("\n")));
    }

    private bool ValidIdentifier(string name) => Identifier(name)
        && _syntax.Format(new WitBindingSyntaxRequest.Variable(name)) != "@" + name;

    private static bool Identifier(string name) => name.Length != 0
        && (char.IsAsciiLetter(name[0]) || name[0] == '_')
        && name.All(character => char.IsAsciiLetterOrDigit(character) || character == '_');

    private const string ClientLifetime = """
        public Task DisposeAsync() => _closing ??= CloseAsync();
        private async Task CloseAsync()
        {
            if (_closed) return;
            _closed = true;
            try { var reader = Response(await Invoke(_session, Request(2).Bytes, default)); reader.End(); }
            finally { ReleaseSession(); }
        }
        private void ReleaseSession() { if (_released) return; _released = true; try { Terminate(_session); } finally { _session.Dispose(); } }
        public void Dispose() { _closed = true; ReleaseSession(); }
        private static Task<byte[]> Invoke(JSObject session, byte[] bytes, CancellationToken cancellationToken)
        {
            var invocation = BeginCall(session, bytes);
            var completion = new TaskCompletionSource<byte[]>();
            JSSubscription? subscription = null; var finished = false;
            void Close() { if (finished) return; finished = true; try { subscription?.Dispose(); } finally { subscription = null; invocation.Dispose(); } }
            void Complete(byte[] response) { if (finished) return; Close(); completion.TrySetResult(response); }
            void Reject() { if (finished) return; Close(); completion.TrySetException(new InvalidOperationException("Worker bridge completion failed.")); }
            try { subscription = Call(invocation, Complete, Reject); } catch { Close(); throw; }
            if (finished) { subscription.Dispose(); subscription = null; }
            var registration = cancellationToken.Register(() => { if (finished) return; try { Cancel(invocation); } finally { Close(); completion.TrySetCanceled(cancellationToken); } });
            return Await();
            async Task<byte[]> Await() { try { return await completion.Task; } finally { registration.Dispose(); Close(); } }
        }
        """;

    private const string JavaScriptLifetime = """
        export function create() {
          const startup = new AbortController(); let current = null; let closed = false; let terminated = false;
          const ready = import(new URL(workerClientModule, import.meta.url).href).then(module => {
            if (module.workerContractFingerprint !== contractFingerprint) throw new Error('Worker client contract does not match. Rebuild and publish the caller and worker together.');
            return module.createWorker({ signal: startup.signal });
          }).then(client => { current = client; if (closed) { client.terminate(); throw new Error('Worker caller is closed.'); } return client; });
          ready.catch(() => {});
          return Object.freeze({ ready,
            async close() { if (closed) return; closed = true; if (current !== null) await current.dispose(); else { startup.abort(); await ready.catch(() => {}); } },
            dispose() { if (terminated) return; terminated = true; closed = true; startup.abort(); current?.terminate(); },
          });
        }
        export function terminate(owner) { owner.dispose(); }
        export function beginCall(owner, bytes) {
          const controller = new AbortController();
          const response = execute(owner, bytes, controller.signal);
          response.catch(() => {});
          return Object.freeze({ response, controller });
        }
        export function cancel(invocation) { invocation.controller.abort(); }
        export function call(invocation) { return invocation.response; }
        """;

    private const string CSharpHeader = """
        private static WireWriter Request(uint action) { var writer = new WireWriter(); Writeu32(writer, 0x3143574eu); Writestring(writer, ContractFingerprint); Writeu32(writer, action); return writer; }
        private static WireReader Response(byte[] bytes)
        {
            var reader = new WireReader(bytes);
            if (Readu32(reader) != 0x3143574eu || Readstring(reader) != ContractFingerprint) throw InvalidWire();
            var status = Readu8(reader);
            if (status == 1) { var message = Readstring(reader); reader.End(); throw new InvalidOperationException(message); }
            if (status != 0) throw InvalidWire(); return reader;
        }
        """;

    private const string JavaScriptHeader = """
        function checkHeader(reader) { if (readu32(reader) !== 0x3143574e || readstring(reader) !== contractFingerprint) throw invalidWire(); }
        function response(status = 0) { const writer = new WireWriter(); writeu32(writer, 0x3143574e); writestring(writer, contractFingerprint); writeu8(writer, status); return writer; }
        """;
}

public static class WitWorkerCSharpClientComposition
{
    public static IWitWorkerCSharpClientWriter CreateWriter()
    {
        var definitions = new TypeDefinitions.WitTypeDefinitionClassifier();
        var syntax = new WitBindingSyntaxFormatter(definitions);
        return new WitWorkerCSharpClientWriter(WitWorkerContractComposition.CreateReader(),
            new WitWorkerCSharpContractProjector(new WitWorkerValueLayoutPlanner()),
            new WitTypeDeclarationWriter(syntax, new CodeWriterFactory(), new Aliases.WitAliasValidator(syntax), definitions),
            syntax, WitWorkerValueCodecComposition.CreateWriters());
    }
}
