using System.Text.Json;
using NetWasm.Hosting.Capabilities;
using NetWasm.Hosting.Deployment;
using NetWasm.Hosting.Generator;

namespace NetWasm.Hosting.Generator.Tests;

public sealed class HostingPlatformCatalogJavaScriptWriterTests
{
    [Fact]
    public void EmitsDeterministicDeeplyFrozenEsmForEveryCapability()
    {
        var providers = Enum.GetValues<NetWasmPlatformCapability>()
            .Select((capability, index) => new NetWasmPlatformImportProvider(
                $"wasi:test/module-{index}@1.0.0",
                capability,
                [new($"wasi:test/module-{index}@1.0.0", "run", ["string"], ["u32"])]))
            .ToArray();
        var catalog = new HostingPlatformCatalog(
            1,
            "wasi:test/command@1.0.0",
            new('a', 64),
            new("@bytecodealliance/preview2-shim", "0.24.1"),
            [.. providers]);

        var source = new HostingPlatformCatalogJavaScriptWriter().Write(catalog);

        Assert.DoesNotContain('\r', source);
        Assert.StartsWith("// Generated by NetWasm.Hosting.Generator. Do not edit.\n", source);
        Assert.Contains("export const platformProviderCatalog = deepFreeze(", source);
        using var json = JsonDocument.Parse(ReadJson(source));
        var root = json.RootElement;
        Assert.Equal(1, root.GetProperty("schema").GetInt32());
        Assert.Equal(catalog.World, root.GetProperty("world").GetString());
        Assert.Equal(catalog.WitSha256, root.GetProperty("witSha256").GetString());
        Assert.Equal(catalog.Shim.Package,
            root.GetProperty("shim").GetProperty("package").GetString());
        Assert.Equal(catalog.Shim.Version,
            root.GetProperty("shim").GetProperty("version").GetString());
        Assert.Equal(
            [
                "baseline", "environment", "preopenedDirectories", "network",
                "wallClock", "monotonicClock", "randomness",
            ],
            root.GetProperty("providers").EnumerateArray()
                .Select(provider => provider.GetProperty("capability").GetString()));
        var function = root.GetProperty("providers")[0].GetProperty("functions")[0];
        Assert.Equal("run", function.GetProperty("name").GetString());
        Assert.Equal("string", function.GetProperty("parameters")[0].GetString());
        Assert.Equal("u32", function.GetProperty("results")[0].GetString());
    }

    [Fact]
    public void RejectsMissingCatalogAndUnknownCapability()
    {
        var writer = new HostingPlatformCatalogJavaScriptWriter();
        Assert.Throws<ArgumentNullException>(() => writer.Write(null!));
        var provider = new NetWasmPlatformImportProvider(
            "wasi:test/api@1.0.0", (NetWasmPlatformCapability)99, []);
        var catalog = new HostingPlatformCatalog(
            1, "world", "hash", new("shim", "version"), [provider]);

        Assert.Throws<InvalidDataException>(() => writer.Write(catalog));
    }

    private static string ReadJson(string source)
    {
        const string marker = "export const platformProviderCatalog = deepFreeze(";
        var start = source.IndexOf(marker, StringComparison.Ordinal) + marker.Length;
        return source[start..source.LastIndexOf(");", StringComparison.Ordinal)];
    }
}
