using Microsoft.Build.Utilities;
using NetWasm.Compiler.Tasks.MsBuild;

namespace NetWasm.Compiler.Tasks.Tests.MsBuild;

public sealed class CompilerArtifactManifestTaskRequestBuilderTests
{
    [Fact]
    public void BuilderMapsInputsAndArtifactMetadata()
    {
        var artifact = new TaskItem("application.core.wasm");
        artifact.SetMetadata("Kind", "CoreModule");
        artifact.SetMetadata("MediaType", "application/wasm");
        var input = new CompilerArtifactManifestTaskInput(
            "obj/manifest.json",
            "/project",
            "netwasm0.1",
            "wasm64",
            "simd",
            "sdk",
            "compiler",
            "abi",
            "runtime",
            "bin/application.dll",
            [new TaskItem("bin/reference.dll")],
            [new TaskItem("Program.cs")],
            "runtime/runtime-abi.json",
            [artifact]);

        var request = new CompilerArtifactManifestTaskRequestBuilder().Build(input);

        Assert.Equal("obj/manifest.json", request.ManifestPath);
        Assert.Equal("/project", request.ProjectDirectory);
        Assert.Equal(["InputAssembly", "Reference", "Source", "RuntimeAbiManifest"], request.Inputs.Select(static item => item.Kind));
        Assert.Equal("bin/application.dll", request.Inputs[0].Path);
        var output = Assert.Single(request.Outputs);
        Assert.Equal("CoreModule", output.Kind);
        Assert.Equal("application/wasm", output.MediaType);
        Assert.Equal("application.core.wasm", output.Path);
    }

    [Fact]
    public void BuilderUsesStableMetadataDefaults()
    {
        var input = new CompilerArtifactManifestTaskInput(
            "manifest.json",
            ".",
            "profile",
            "wasm32",
            "none",
            "sdk",
            "compiler",
            "abi",
            "runtime",
            "app.dll",
            [],
            [],
            null,
            [new TaskItem("app.wasm")]);

        var request = new CompilerArtifactManifestTaskRequestBuilder().Build(input);

        var output = Assert.Single(request.Outputs);
        Assert.Equal("Unknown", output.Kind);
        Assert.Equal("application/octet-stream", output.MediaType);
    }

    [Fact]
    public void BuilderExcludesGeneratedCompileItemsFromNoBuildFreshness()
    {
        var authored = new TaskItem("Program.cs");
        var autoGenerated = new TaskItem("generated/Application.AssemblyInfo.cs");
        autoGenerated.SetMetadata("AutoGen", "true");
        var generatedUnderRoot = new TaskItem("obj/TargetFrameworkAttributes.cs");
        var input = new CompilerArtifactManifestTaskInput(
            "manifest.json",
            ".",
            "profile",
            "wasm32",
            "none",
            "sdk",
            "compiler",
            "abi",
            "runtime",
            "app.dll",
            [],
            [authored, autoGenerated, generatedUnderRoot],
            null,
            [],
            "obj");

        var request = new CompilerArtifactManifestTaskRequestBuilder().Build(input);

        var source = Assert.Single(request.Inputs, static item => item.Kind == "Source");
        Assert.Equal("Program.cs", source.Path);
    }
}
