<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(TargetFramework)' == 'netwasm0.1'">
    <NetWasmRuntimeTarget>wasm32</NetWasmRuntimeTarget>
    <NetWasmRuntimeCoreLibPath>$([System.IO.Path]::Combine('$(MSBuildThisFileDirectory)', '..', 'runtime', 'NetWasm.CoreLib.dll'))</NetWasmRuntimeCoreLibPath>
    <NetWasmRuntimeAbiManifestPath>$([System.IO.Path]::Combine('$(MSBuildThisFileDirectory)', '..', 'runtime', 'runtime-abi.json'))</NetWasmRuntimeAbiManifestPath>
  </PropertyGroup>
</Project>
