using System;

namespace NetWasm.Wit.Bindings;

public interface IWitCSharpBindingGenerator
{
    string Generate(WitDocument document, WitWorld world);
}

public sealed class WitCSharpBindingGenerator(
    IWitWorldValidator validator,
    IWitTypeDeclarationWriter typeDeclarations,
    IWitBindingMethodWriter bindingMethods,
    IWitCanonicalMarshallingWriter marshalling,
    IWitBindingSyntaxFormatter syntax,
    ICodeWriterFactory writers) : IWitCSharpBindingGenerator
{
    private readonly IWitWorldValidator _validator = validator ??
        throw new ArgumentNullException(nameof(validator));
    private readonly IWitTypeDeclarationWriter _typeDeclarations = typeDeclarations ??
        throw new ArgumentNullException(nameof(typeDeclarations));
    private readonly IWitBindingMethodWriter _bindingMethods = bindingMethods ??
        throw new ArgumentNullException(nameof(bindingMethods));
    private readonly IWitCanonicalMarshallingWriter _marshalling = marshalling ??
        throw new ArgumentNullException(nameof(marshalling));
    private readonly IWitBindingSyntaxFormatter _syntax = syntax ??
        throw new ArgumentNullException(nameof(syntax));
    private readonly ICodeWriterFactory _writers = writers ??
        throw new ArgumentNullException(nameof(writers));

    public string Generate(WitDocument document, WitWorld world)
    {
        ArgumentNullException.ThrowIfNull(document);
        ArgumentNullException.ThrowIfNull(world);
        _validator.Validate(document, world);

        var writer = _writers.Create();
        writer.Line("// <auto-generated />");
        writer.Line("#nullable enable");
        writer.Line("using System;");
        writer.Line("using System.Runtime.InteropServices.WebAssembly;");
        writer.Line();
        writer.Line($"namespace {_syntax.Format(
            new WitBindingSyntaxRequest.PackageNamespace(world.Package))};");
        writer.Line();
        writer.Raw(_typeDeclarations.Generate(document, world));
        writer.Raw(_bindingMethods.Generate(document, world));
        writer.Raw(_marshalling.Generate(document, world));
        return writer.Text;
    }
}
