<Project>
  <PropertyGroup>
    <NetWasmCompilerTasksPackageVersion Condition="'$(NetWasmCompilerTasksPackageVersion)' == ''">0.1.0</NetWasmCompilerTasksPackageVersion>
    <NetWasmHostToolsPackageVersion Condition="'$(NetWasmHostToolsPackageVersion)' == ''">0.1.0</NetWasmHostToolsPackageVersion>
  </PropertyGroup>
</Project>
