<Project>
  <PropertyGroup>
    <NetWasmCompilerTasksPackageVersion Condition="'$(NetWasmCompilerTasksPackageVersion)' == ''">0.4.2</NetWasmCompilerTasksPackageVersion>
    <NetWasmHostToolsPackageVersion Condition="'$(NetWasmHostToolsPackageVersion)' == ''">0.4.2</NetWasmHostToolsPackageVersion>
  </PropertyGroup>
</Project>
