// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices.WebAssembly;

namespace NetWasm.Wit.Netwasm.Worker.Template._1._0._0;

public static class NotificationsImports
{
    public static void Report(uint completed, uint total)
    {
        __CanonicalNetwasmWorkerTemplate100Notifications_Report(unchecked((int)(completed)), unchecked((int)(total)));
    }

    [WitImport("netwasm:worker-template@1.0.0/notifications", "report")]
    private static extern void __CanonicalNetwasmWorkerTemplate100Notifications_Report(int __f0, int __f1);

}

public static partial class ApplicationExports
{
    public static partial uint Run(uint total);

    [WitExport("netwasm:worker-template@1.0.0/work", "run")]
    private static int __CanonicalNetwasmWorkerTemplate100Work_Run(int __f0)
    {
        var __managed0 = unchecked((uint)(__f0));
        var __managedResult = Run(__managed0);
        return unchecked((int)(__managedResult));
    }

    [WitPostReturn("netwasm:worker-template@1.0.0/work", "run")]
    private static void __CanonicalNetwasmWorkerTemplate100Work_RunPost(int __result)
    {
    }

}
