using System.Buffers;
using System.Text;
using System.Text.Json;
using NetWasm.Hosting.Capabilities;

namespace NetWasm.Hosting.Generator;

internal interface IHostingPlatformCatalogJavaScriptWriter
{
    string Write(HostingPlatformCatalog catalog);
}

internal sealed class HostingPlatformCatalogJavaScriptWriter :
    IHostingPlatformCatalogJavaScriptWriter
{
    public string Write(HostingPlatformCatalog catalog)
    {
        ArgumentNullException.ThrowIfNull(catalog);
        var buffer = new ArrayBufferWriter<byte>();
        using (var writer = new Utf8JsonWriter(buffer, new()
        {
            Indented = true,
        }))
        {
            WriteCatalog(writer, catalog);
        }

        return """
            // Generated by NetWasm.Hosting.Generator. Do not edit.
            function deepFreeze(value) {
              for (const child of Object.values(value)) {
                if (child !== null && typeof child === "object") deepFreeze(child);
              }
              return Object.freeze(value);
            }

            export const platformProviderCatalog = deepFreeze(
            """
            + Encoding.UTF8.GetString(buffer.WrittenSpan)
            + """
            );

            """;
    }

    private static void WriteCatalog(Utf8JsonWriter writer, HostingPlatformCatalog catalog)
    {
        writer.WriteStartObject();
        writer.WriteNumber("schema", catalog.Schema);
        writer.WriteString("world", catalog.World);
        writer.WriteString("witSha256", catalog.WitSha256);
        writer.WriteStartObject("shim");
        writer.WriteString("package", catalog.Shim.Package);
        writer.WriteString("version", catalog.Shim.Version);
        writer.WriteEndObject();
        writer.WriteStartArray("providers");
        foreach (var provider in catalog.Providers)
        {
            writer.WriteStartObject();
            writer.WriteString("module", provider.Module);
            writer.WriteString("capability", FormatCapability(provider.Capability));
            writer.WriteStartArray("functions");
            foreach (var function in provider.Functions)
            {
                writer.WriteStartObject();
                writer.WriteString("interface", function.Interface);
                writer.WriteString("name", function.Name);
                WriteStrings(writer, "parameters", function.Parameters);
                WriteStrings(writer, "results", function.Results);
                writer.WriteEndObject();
            }
            writer.WriteEndArray();
            writer.WriteEndObject();
        }
        writer.WriteEndArray();
        writer.WriteEndObject();
    }

    private static void WriteStrings(
        Utf8JsonWriter writer,
        string name,
        IEnumerable<string> values)
    {
        writer.WriteStartArray(name);
        foreach (var value in values)
        {
            writer.WriteStringValue(value);
        }
        writer.WriteEndArray();
    }

    private static string FormatCapability(NetWasmPlatformCapability capability) =>
        capability switch
        {
            NetWasmPlatformCapability.Baseline => "baseline",
            NetWasmPlatformCapability.Environment => "environment",
            NetWasmPlatformCapability.PreopenedDirectories => "preopenedDirectories",
            NetWasmPlatformCapability.Network => "network",
            NetWasmPlatformCapability.WallClock => "wallClock",
            NetWasmPlatformCapability.MonotonicClock => "monotonicClock",
            NetWasmPlatformCapability.Randomness => "randomness",
            _ => throw new InvalidDataException(
                $"Platform capability '{capability}' cannot be emitted."),
        };
}
