using NetWasm.Wit.Bindings;

namespace NetWasm.Wit.Bindings.Tests;

public sealed class WitProgramTests
{
    [Fact]
    public void MainGeneratesBindingsAndReportsBindingDiagnostics()
    {
        var directory = Directory.CreateTempSubdirectory("netwasm-wit-bindings-");
        try
        {
            var witPath = Path.Combine(directory.FullName, "contract.wit");
            var outputPath = Path.Combine(directory.FullName, "Bindings.g.cs");
            File.WriteAllText(
                witPath,
                "package example:test@1.0.0;\nworld main {}\n");

            Assert.Equal(
                0,
                Program.Main(["--wit", witPath, "--output", outputPath]));
            Assert.Contains("// <auto-generated />", File.ReadAllText(outputPath),
                StringComparison.Ordinal);

            var originalError = Console.Error;
            using var diagnostics = new StringWriter();
            Console.SetError(diagnostics);
            try
            {
                Assert.Equal(1, Program.Main(["--wit"]));
            }
            finally
            {
                Console.SetError(originalError);
            }

            Assert.Contains("missing value", diagnostics.ToString(),
                StringComparison.Ordinal);
        }
        finally
        {
            directory.Delete(recursive: true);
        }
    }
}
